name: Create Release Zip
on:
  release:
    types: [created]
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create zip file
        run: |
          mkdir release
          cp -r Reference/*.bpmn LICENSE.txt README.md release/
          cd release
          zip -r ../release.zip .
          cd ..

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: bpmn-miwg-test-suite-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
